# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 15:22
from __future__ import unicode_literals

import DjangoUeditor.models
import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('title_img', models.ImageField(blank=True, null=True, upload_to=article.models.upload_to_goods_img, verbose_name='图片')),
                ('body_type', models.PositiveSmallIntegerField(choices=[(0, 'Ueditor'), (1, 'MarkDown')], default=0, verbose_name='内容类型')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='内容详情')),
                ('body_1', models.TextField(blank=True, null=True, verbose_name='内容详情(MarkDown)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读数')),
                ('status', models.IntegerField(choices=[(0, '显示'), (1, '禁用')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(verbose_name='发表时间')),
                ('update_time', models.DateTimeField(verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('status', models.IntegerField(choices=[(0, '启用'), (1, '关闭')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='article.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='article.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
