# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_time'], 'verbose_name': '文章信息', 'verbose_name_plural': '文章信息'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag标签', 'verbose_name_plural': 'Tag标签'},
        ),
    ]
